# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55b14aa2ab0c315b64a72524e167c265"
name = "product-channel-guard"
application_url = "https://product-channel-guard.onrender.com"
embedded = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_publications,write_publications"

[auth]
redirect_urls = ["https://product-channel-guard.onrender.com/api/auth/callback"]

[build]
automatically_update_urls_on_dev = true

[webhooks.privacy_compliance]
customer_data_request_url = "https://product-channel-guard.onrender.com/api/webhooks"
customer_deletion_url = "https://product-channel-guard.onrender.com/api/webhooks"
shop_deletion_url = "https://product-channel-guard.onrender.com/api/webhooks"